version: '3.8'
services:
  myapp:
    container_name: myapp
    build:
      context: my_app/.
      dockerfile: Dockerfile
    environment:
      MLFLOW_SERVER: http://mlflow_server:5000
      MLFLOW_REGISTRY_NAME: purchase_predict
    command: ["python3", "/app/app.py"]
    networks:
      - mlflow_network
    ports:
      - "9000:9000"

  mlflow_server:
    container_name: mlflow
    build:
      context: mlflow/.
      dockerfile: Dockerfile
    networks:
      - mlflow_network
    ports:
      - "5000:5000" 


networks:
  mlflow_network:
    external: true 