version: '3.8'
services:
  mlflow:
    build:
      context: mlflow/.
      dockerfile: Dockerfile
    image: mlflow_server
    container_name: mlflow_server
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    command: ["mlflow", "server", "--host", "0.0.0.0"]
    ports:
      - "5000:5000"  # Maps port 5000 of the container to port 8080 on the host
    networks:
      - mlflow_network

  myapp:
    build:
      context: my_app/.
      dockerfile: Dockerfile
    environment:
      MLFLOW_SERVER: http://mlflow:5000
      MLFLOW_REGISTRY_NAME: purchase_predict
    command: ["python3", "/app/app.py"]
    depends_on:
      - mlflow
    ports:
      - "9000:9000"
    networks:
      - mlflow_network

networks:
  mlflow_network:
    driver: bridge